// Copyright 2026 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

// gen-builtins reads a JSON builtin catalog (produced by extract-builtins)
// and emits a Go source file containing builtinsregistry.Register() calls
// for each function. The generated code registers metadata-only stubs with
// no Fn closures, enabling function-name validation and overload resolution
// without a live database.
//
// Usage:
//
//	go run ./cmd/gen-builtins \
//	  -input  internal/builtinstubs/testdata/crdb_builtins_v26.2.json \
//	  -output internal/builtinstubs/stubs_v26_2_gen.go \
//	  -version v26.2
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"text/template"
)

type catalog struct {
	Version   string     `json:"version"`
	Functions []function `json:"functions"`
}

type function struct {
	Name       string     `json:"name"`
	Properties properties `json:"properties"`
	Overloads  []overload `json:"overloads"`
}

type properties struct {
	Category                string `json:"category,omitempty"`
	AvailableOnPublicSchema bool   `json:"available_on_public_schema,omitempty"`
	Undocumented            bool   `json:"undocumented,omitempty"`
}

type overload struct {
	Params         []param `json:"params,omitempty"`
	ParamKind      string  `json:"param_kind"`
	VariadicType   *typ    `json:"variadic_type,omitempty"`
	ReturnType     *typ    `json:"return_type,omitempty"`
	ReturnTypeKind string  `json:"return_type_kind"`
	Volatility     string  `json:"volatility"`
	Class          string  `json:"class"`
	CalledOnNull   bool    `json:"called_on_null_input,omitempty"`
	Preference     int     `json:"preference,omitempty"`
}

type param struct {
	Name string `json:"name,omitempty"`
	Type typ    `json:"type"`
}

type typ struct {
	OID    uint32 `json:"oid"`
	Name   string `json:"name"`
	Family string `json:"family,omitempty"`
}

// oidToGoExpr maps OIDs to Go expressions that resolve to *types.T.
// The generator uses types.OidToType for most OIDs, but some pseudo-types
// and special types need explicit named references.
var oidToGoExpr = map[uint32]string{
	0:     "types.Any",
	16:    "types.Bool",
	17:    "types.Bytes",
	18:    "types.QChar",
	19:    "types.Name",
	20:    "types.Int",
	21:    "types.Int2",
	22:    "types.Int2Vector",
	23:    "types.Int4",
	24:    "types.RegProc",
	25:    "types.String",
	26:    "types.Oid",
	30:    "types.OidVector",
	700:   "types.Float4",
	701:   "types.Float",
	705:   "types.Unknown",
	869:   "types.INet",
	1042:  "types.BPChar",
	1043:  "types.VarChar",
	1082:  "types.Date",
	1083:  "types.Time",
	1114:  "types.Timestamp",
	1184:  "types.TimestampTZ",
	1186:  "types.Interval",
	1266:  "types.TimeTZ",
	1560:  "types.MakeBit(0)",
	1562:  "types.VarBit",
	1700:  "types.Decimal",
	1790:  "types.RefCursor",
	2202:  "types.RegProcedure",
	2205:  "types.RegClass",
	2206:  "types.RegType",
	2249:  "types.AnyTuple",
	2276:  "types.Any",
	2277:  "types.AnyArray",
	2278:  "types.Void",
	2279:  "types.Trigger",
	2283:  "types.AnyElement",
	2950:  "types.Uuid",
	3220:  "types.PGLSN",
	3500:  "types.AnyEnum",
	3614:  "types.TSVector",
	3615:  "types.TSQuery",
	3802:  "types.Jsonb",
	4072:  "types.Jsonpath",
	4089:  "types.RegNamespace",
	4096:  "types.RegRole",
	90000: "types.Geometry",
	90002: "types.Geography",
	90004: "types.Box2D",
	90006: "types.PGVector",
	90008: "types.CIText",
	90010: "types.LTree",
}

func typeExpr(t typ) string {
	if expr, ok := oidToGoExpr[t.OID]; ok {
		return expr
	}
	// For array types, use types.MakeArray with the element type.
	// Array OIDs in postgres are generally the element OID's array variant.
	// We use OidToType as the runtime fallback.
	return fmt.Sprintf("oidTyp(%d)", t.OID)
}

func volatilityExpr(v string) string {
	switch v {
	case "immutable":
		return "volatility.Immutable"
	case "stable":
		return "volatility.Stable"
	case "volatile":
		return "volatility.Volatile"
	default:
		return "volatility.Volatile"
	}
}

func classExpr(c string) string {
	switch c {
	case "normal":
		return "tree.NormalClass"
	case "aggregate":
		return "tree.AggregateClass"
	case "window":
		return "tree.WindowClass"
	case "generator":
		return "tree.GeneratorClass"
	default:
		return "tree.NormalClass"
	}
}

func versionToIdent(v string) string {
	r := strings.NewReplacer(".", "_", "-", "_")
	return r.Replace(strings.TrimPrefix(v, "v"))
}

func goStringLit(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

var funcMap = template.FuncMap{
	"typeExpr":       typeExpr,
	"volatilityExpr": volatilityExpr,
	"classExpr":      classExpr,
	"goStringLit":    goStringLit,
}

var tmpl = template.Must(template.New("stubs").Funcs(funcMap).Parse(`// Code generated by gen-builtins from {{.InputFile}}; DO NOT EDIT.

package builtinstubs

import (
	"github.com/cockroachdb/cockroachdb-parser/pkg/sql/sem/builtins/builtinsregistry"
	"github.com/cockroachdb/cockroachdb-parser/pkg/sql/sem/tree"
	"github.com/cockroachdb/cockroachdb-parser/pkg/sql/sem/volatility"
	"github.com/cockroachdb/cockroachdb-parser/pkg/sql/types"
)

// oidTyp is shared across versions; see internal/builtinstubs/typehelpers.go.

func registerV{{.VersionIdent}}() {
{{- range .Functions}}
	builtinsregistry.Register({{goStringLit .Name}}, &tree.FunctionProperties{
{{- if .Properties.Category}}
		Category: {{goStringLit .Properties.Category}},
{{- end}}
{{- if .Properties.AvailableOnPublicSchema}}
		AvailableOnPublicSchema: true,
{{- end}}
{{- if .Properties.Undocumented}}
		Undocumented: true,
{{- end}}
	}, []tree.Overload{
{{- range .Overloads}}
		{
{{- if eq .ParamKind "fixed"}}
{{- if .Params}}
			Types: tree.ParamTypes{
{{- range .Params}}
				{Name: {{goStringLit .Name}}, Typ: {{typeExpr .Type}}},
{{- end}}
			},
{{- else}}
			Types: tree.ParamTypes{},
{{- end}}
{{- else if eq .ParamKind "homogeneous"}}
			Types: tree.HomogeneousType{},
{{- else if eq .ParamKind "variadic"}}
			Types: tree.VariadicType{
{{- if .Params}}
				FixedTypes: []*types.T{
{{- range .Params}}
					{{typeExpr .Type}},
{{- end}}
				},
{{- end}}
				VarType: {{typeExpr .VariadicType}},
			},
{{- end}}
			ReturnType:       tree.FixedReturnType({{typeExpr .ReturnType}}),
			Volatility:       {{volatilityExpr .Volatility}},
			Class:            {{classExpr .Class}},
{{- if .CalledOnNull}}
			CalledOnNullInput: true,
{{- end}}
{{- if ne .Preference 0}}
			OverloadPreference: tree.OverloadPreference({{.Preference}}),
{{- end}}
		},
{{- end}}
	})
{{end -}}
}
`))

type templateData struct {
	InputFile    string
	VersionIdent string
	Functions    []function
}

func main() {
	inputFile := flag.String("input", "", "path to JSON catalog file")
	outputFile := flag.String("output", "", "path to output Go file")
	version := flag.String("version", "", "CRDB version (e.g., v26.2)")
	flag.Parse()

	if *inputFile == "" || *outputFile == "" || *version == "" {
		log.Fatal("usage: gen-builtins -input FILE -output FILE -version VERSION")
	}

	data, err := os.ReadFile(*inputFile)
	if err != nil {
		log.Fatalf("reading input: %v", err)
	}

	var cat catalog
	if err := json.Unmarshal(data, &cat); err != nil {
		log.Fatalf("parsing JSON: %v", err)
	}

	sort.Slice(cat.Functions, func(i, j int) bool {
		return cat.Functions[i].Name < cat.Functions[j].Name
	})

	// Filter out functions with no overloads.
	var filtered []function
	for _, f := range cat.Functions {
		if len(f.Overloads) > 0 {
			filtered = append(filtered, f)
		}
	}

	td := templateData{
		InputFile:    *inputFile,
		VersionIdent: versionToIdent(*version),
		Functions:    filtered,
	}

	out, err := os.Create(*outputFile)
	if err != nil {
		log.Fatalf("creating output: %v", err)
	}

	if err := tmpl.Execute(out, td); err != nil {
		_ = out.Close()
		log.Fatalf("executing template: %v", err)
	}
	if err := out.Close(); err != nil {
		log.Fatalf("closing output: %v", err)
	}

	fmt.Fprintf(os.Stderr, "generated %s: %d functions, %d overloads\n",
		*outputFile, len(td.Functions), countOverloads(td.Functions))
}

func countOverloads(funcs []function) int {
	n := 0
	for _, f := range funcs {
		n += len(f.Overloads)
	}
	return n
}
