#!/usr/bin/env bash
# Recompute wave-N labels on open GitHub issues from their declared
# dependency edges. Run this after creating, closing, or editing any
# issue whose "## Dependencies" block changes.
#
# Source of truth: each open issue body contains a section like
#
#   ## Dependencies
#   - **Depends on:** #6, #8, #11
#   - **Blocks:** #14, #15, #16
#
# This script reads the "Depends on:" line, ignores closed and missing
# refs, and assigns wave[i] = 0 if all deps are resolved, else
# wave[i] = 1 + max(wave[d] for d in open deps). The matching wave-N
# label is applied to each issue (creating new wave-N labels on demand);
# stale wave-* labels are removed.
#
# Wave numbers are NEVER written into issue bodies — they would rot the
# moment a new edge is added. The label is the single canonical view.
#
# Usage:
#   scripts/issue-graph.sh                      # current repo
#   scripts/issue-graph.sh owner/repo           # explicit repo
set -euo pipefail

REPO_ARGS=()
if [[ $# -gt 0 ]]; then REPO_ARGS=(--repo "$1"); fi

for cmd in gh jq; do
  if ! command -v "$cmd" >/dev/null; then
    echo "error: '$cmd' is required" >&2
    exit 1
  fi
done

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Fetch open issues as TSV: number<TAB>deps_csv<TAB>wave_labels_csv.
# deps_csv is the comma-joined #-references found on the "Depends on:"
# line (empty if none or if the section is absent).
gh issue list "${REPO_ARGS[@]}" --state open --limit 500 \
  --json number,body,labels \
  --jq '
    .[] | [
      (.number | tostring),
      ( ( .body // "" )
        | ( ( try ( match("Depends on:[^\n]*") | .string ) catch "" ) // "" )
        | [ scan("#[0-9]+") ]
        | map(ltrimstr("#"))
        | join(",")
      ),
      ( [ .labels[].name | select(test("^wave-[0-9]+$")) ] | join(",") )
    ] | join("|")
  ' > "$tmp/issues.tsv"

# Closed issue numbers — treated as "resolved" and excluded from max().
gh issue list "${REPO_ARGS[@]}" --state closed --limit 1000 \
  --json number --jq '.[].number' > "$tmp/closed.txt"

declare -A DEPS WAVE LABELS OPEN VISITING CLOSED

while IFS='|' read -r num deps labels; do
  OPEN[$num]=1
  DEPS[$num]=$deps
  LABELS[$num]=$labels
done < "$tmp/issues.tsv"

while read -r c; do CLOSED[$c]=1; done < "$tmp/closed.txt"

# Topo-sort with memoization. Bails on cycles.
compute() {
  local n=$1
  if [[ -n "${WAVE[$n]:-}" ]]; then echo "${WAVE[$n]}"; return; fi
  if [[ "${VISITING[$n]:-}" == 1 ]]; then
    echo "error: dependency cycle involving #$n" >&2
    exit 1
  fi
  VISITING[$n]=1
  local max=-1 d dw
  IFS=',' read -ra darr <<< "${DEPS[$n]}"
  for d in "${darr[@]}"; do
    [[ -z $d ]] && continue
    [[ -n "${CLOSED[$d]:-}" ]] && continue
    if [[ -z "${OPEN[$d]:-}" ]]; then
      echo "warn: #$n depends on missing/unknown #$d (treating as resolved)" >&2
      continue
    fi
    dw=$(compute "$d")
    (( dw > max )) && max=$dw
  done
  WAVE[$n]=$((max + 1))
  VISITING[$n]=0
  echo "${WAVE[$n]}"
}

for n in "${!OPEN[@]}"; do compute "$n" >/dev/null; done

# Ensure every wave-N label that we plan to apply exists.
declare -A NEEDED
for n in "${!OPEN[@]}"; do NEEDED["wave-${WAVE[$n]}"]=1; done

existing=$(gh label list "${REPO_ARGS[@]}" --limit 200 \
  --json name --jq '.[].name')
for label in "${!NEEDED[@]}"; do
  if ! grep -qx "$label" <<< "$existing"; then
    gh label create "$label" "${REPO_ARGS[@]}" \
      --description "Auto-generated by issue-graph.sh" \
      --color "ededed" >/dev/null
    echo "created label $label"
  fi
done

# Apply label changes. Removes any stale wave-* labels and adds the
# computed one.
changed=0
for n in "${!OPEN[@]}"; do
  want="wave-${WAVE[$n]}"
  current_csv="${LABELS[$n]}"
  IFS=',' read -ra current_arr <<< "$current_csv"

  # Skip if the only current wave label already matches.
  if [[ "${#current_arr[@]}" -eq 1 && "${current_arr[0]}" == "$want" ]]; then
    continue
  fi

  args=(issue edit "$n" "${REPO_ARGS[@]}" --add-label "$want")
  for old in "${current_arr[@]}"; do
    [[ -z $old || $old == "$want" ]] && continue
    args+=(--remove-label "$old")
  done
  gh "${args[@]}" >/dev/null
  printf '#%s  %s -> %s\n' "$n" "${current_csv:-<none>}" "$want"
  ((++changed))
done

echo "updated $changed of ${#OPEN[@]} open issues."
